name: Build

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Configure CMake
        run: cmake -B build -A x64 -DCMAKE_BUILD_TYPE=Debug
      - name: Build server and client
        run: cmake --build build --config Debug --target gmsv_hordeengine_win64 gmcl_hordeengine_win64
      - name: Upload DLLs
        uses: actions/upload-artifact@v4
        with:
          name: hordeengine-dlls
          path: |
            build/bin/server/x64/Debug/gmsv_hordeengine_win64.dll
            build/bin/client/x64/Debug/gmcl_hordeengine_win64.dll
