name: Release HordeEngine

on:
  push:
    tags: [ '*' ]   # trigger on ANY tag, e.g. v1.0.0

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake (x64 Release)
        run: cmake -S . -B build -A x64 -DGMOD_MODULE_BASE_INCLUDE="C:/Users/John Sonnier/Desktop/gmod-module-base/include"

      - name: Build
        run: cmake --build build --config Release

      - name: Collect package contents (DLLs + Lua + README + scripts)
        shell: cmd
        run: |
          if exist package rmdir /s /q package
          mkdir package
          copy /Y build\bin\Release\gmcl_hordeengine_win64.dll package\
          copy /Y build\bin\Release\gmsv_hordeengine_win64.dll package\
          copy /Y lua\autorun\*.lua package\
          copy /Y README.md package\
          xcopy scripts package\scripts\ /E /I /Y

      - name: Create zips (versioned + latest)
        run: |
          $tag='${{ github.ref_name }}'
          Compress-Archive -Path package\* -DestinationPath ("HordeEngine-" + $tag + ".zip") -Force
          Compress-Archive -Path package\* -DestinationPath "HordeEngine-latest.zip" -Force

      - name: Publish GitHub Release (auto notes, attach both zips)
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ github.ref_name }}"
          tag_name: ${{ github.ref_name }}
          files: |
            HordeEngine-${{ github.ref_name }}.zip
            HordeEngine-latest.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
